spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dota
    username: DOTA_BAGS
    password: DOTA_BAGS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: 'DOTA_BAGS'
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'dulovicnika27@gmail.com'
    password: 'bfdg emsj scao egsi'
    smtp:
      ssl:
        protocols: 'TLSv1.2'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration

file:
  upload-dir: ${FILE_UPLOAD_DIR}

mail:
  order:
    arrived:
      subject: 'New order'

aws:
  region: 'eu-central-1'
  s3:
    bucket: 'dota-bucket-test'
    image-url-prefix: 'https://dota-bucket-test.s3.eu-central-1.amazonaws.com'
    root-folder: 'images'
