spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /dota

custom:
  token: ${CUSTOM_TOKEN}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: never

mail:
  recipients:
    - ${MAIL_USERNAME}
  order:
    arrived:
      subject: 'New order'
    excel:
      daily-subject: 'All orders made in past 24h'
      monthly-subject: 'All orders made in a previous month'
  contact-form:
    subject: 'New message from contact form'
  newsletter:
    subject: 'Newsletter subscriptions made in past 24h'
    conformation:
      subject: 'Subscription Confirmation'
    unsubscribe:
      subject: 'Unsubscribe Confirmation'
    excel:
      subject: 'All subscriptions made in a previous month'

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET_NAME}
    image-url-prefix: ${AWS_IMAGE_URL}
    root-folder: 'images'

app:
  protocol: ${PROTOCOL}
  host: ${HOST}
  base-url: '${app.protocol}://${app.host}:${server.port}'
  newsletter:
    unsubscribe-path: '/dota/newsletter/unsubscribe'
  health-check:
    rate: ${HEALTH_CHECK_RATE}

origin:
  allowed: ${ORIGIN_ALLOWED}

excel:
  sheet:
    name: 'Orders'

newsletter:
  unsubscribe:
    successful: 'You unsubscribed successfully.'
    unsuccessful: 'Your unsubscribe request was not executed successfully.'