spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /dota

mail:
  recipients:
    - ${MAIL_USERNAME}
  order:
    arrived:
      subject: 'New order'
    excel:
      daily-subject: 'All orders made in past 24h'
      monthly-subject: 'All orders made in a previous month'
  contact-form:
    subject: 'New message from contact form'
  newsletter:
    subject: 'Newsletter subscriptions made in past 24h'

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET_NAME}
    image-url-prefix: ${AWS_IMAGE_URL}
    root-folder: 'images'

excel:
  sheet:
    name: 'Orders'

